# Generated by Django 5.0.6 on 2024-06-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='street_detail',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
