# Generated by Django 5.0.6 on 2024-06-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_street_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='users/default-avatar.png', null=True, upload_to='users/'),
        ),
    ]
