# Generated by Django 5.0.6 on 2024-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycollection',
            name='price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
