# Generated by Django 5.0.6 on 2024-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_emergencycollection_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycollection',
            name='paid',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
