# Generated by Django 5.0.6 on 2024-06-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_emergencycollection_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycollection',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
