# Generated by Django 5.0.6 on 2024-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_emergencycollection_town_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
