# Generated by Django 5.0.6 on 2024-06-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_companyprofile_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllegalDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='illegal_deposit_images/')),
                ('description', models.TextField()),
                ('town_street', models.CharField(choices=[('Yaounde, Bastos', 'Yaounde, Bastos'), ('Yaounde, Nkolbisson', 'Yaounde, Nkolbisson'), ('Yaounde, Ngoa-Ekelle', 'Yaounde, Ngoa-Ekelle'), ('Yaounde, Mvog-Ada', 'Yaounde, Mvog-Ada'), ('Yaounde, Mvog-Mbi', 'Yaounde, Mvog-Mbi'), ('Yaounde, Etoudi', 'Yaounde, Etoudi'), ('Yaounde, Nsam', 'Yaounde, Nsam'), ('Yaounde, Essos', 'Yaounde, Essos'), ('Yaounde, Biyemassi', 'Yaounde, Biyemassi'), ('Yaounde, Mendong', 'Yaounde, Mendong'), ('Yaounde, Emana', 'Yaounde, Emana'), ('Yaounde, Ahala', 'Yaounde, Ahala'), ('Yaounde, Oyom-Abang', 'Yaounde, Oyom-Abang'), ('Yaounde, Nkolndongo', 'Yaounde, Nkolndongo'), ('Yaounde, Ekounou', 'Yaounde, Ekounou'), ('Yaounde, Obili', 'Yaounde, Obili'), ('Yaounde, Etoa-Meki', 'Yaounde, Etoa-Meki'), ('Yaounde, Melen', 'Yaounde, Melen'), ('Yaounde, Odza', 'Yaounde, Odza'), ('Yaounde, Mfandena', 'Yaounde, Mfandena'), ('Yaounde, Biyem-Assi', 'Yaounde, Biyem-Assi'), ('Yaounde, Nkol-Eton', 'Yaounde, Nkol-Eton'), ('Yaounde, Mvan', 'Yaounde, Mvan'), ('Yaounde, Tsinga', 'Yaounde, Tsinga'), ('Yaounde, Messa', 'Yaounde, Messa'), ('Yaounde, Simbock', 'Yaounde, Simbock'), ('Yaounde, Ngousso', 'Yaounde, Ngousso'), ('Yaounde, Etoug-Ebe', 'Yaounde, Etoug-Ebe'), ('Yaounde, Anguissa', 'Yaounde, Anguissa'), ('Yaounde, Awae', 'Yaounde, Awae'), ('Yaounde, Nfandena', 'Yaounde, Nfandena'), ('Yaounde, Biassi', 'Yaounde, Biassi'), ('Yaounde, Efoulan', 'Yaounde, Efoulan'), ('Yaounde, Essomba', 'Yaounde, Essomba'), ('Yaounde, Olezoa', 'Yaounde, Olezoa'), ('Yaounde, Nyom', 'Yaounde, Nyom'), ('Yaounde, Mimboman', 'Yaounde, Mimboman'), ('Yaounde, Nkolmesseng', 'Yaounde, Nkolmesseng'), ('Yaounde, Madagascar', 'Yaounde, Madagascar'), ('Yaounde, Tsinga', 'Yaounde, Tsinga'), ('Yaounde, Elig-Essono', 'Yaounde, Elig-Essono'), ('Yaounde, Simbok', 'Yaounde, Simbok'), ('Yaounde, Mbankolo', 'Yaounde, Mbankolo'), ('Yaounde, Ekoumdoum', 'Yaounde, Ekoumdoum'), ('Yaounde, Nkoabang', 'Yaounde, Nkoabang'), ('Yaounde, Nkoldongo', 'Yaounde, Nkoldongo'), ('Yaounde, Abattoir', 'Yaounde, Abattoir'), ('Yaounde, Odza', 'Yaounde, Odza'), ('Yaounde, Cite Verte', 'Yaounde, Cite Verte'), ('Yaounde, Ngousso', 'Yaounde, Ngousso'), ('Yaounde, Nkomo', 'Yaounde, Nkomo'), ('Douala, Nkomo', 'Douala, Nkomo')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('street_detail', models.CharField(max_length=255)),
            ],
        ),
    ]
